#!/usr/local/bin/python3

"""
    Copyright (c) 2022 Ad Schellevis <ad@opnsense.org>
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    1. Redistributions of source code must retain the above copyright notice,
     this list of conditions and the following disclaimer.

    2. Redistributions in binary form must reproduce the above copyright
     notice, this list of conditions and the following disclaimer in the
     documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
"""

import os
import sys
import json
import subprocess

config_filename = '/usr/local/etc/ddclient.json'
status_filename = '/var/tmp/ddclient_opn.status'
backends_dir = '/usr/local/opnsense/scripts/ddclient/backends'

# the backend in use is resolved by the template generating our configuration
backend = 'opnsense'
if os.path.isfile(config_filename):
    try:
        with open(config_filename) as f:
            backend = json.load(f).get('general', {}).get('backend', 'opnsense')
    except ValueError:
        pass

backend_stats = '%s/%s_stats' % (backends_dir, backend)
if backend != 'opnsense' and os.path.isfile(backend_stats):
    sys.stdout.write(subprocess.run([sys.executable, backend_stats], capture_output=True, text=True).stdout)
    sys.exit(0)

result = {"hosts": {}}
if os.path.isfile(status_filename):
    # output will look completely different when our implementation is used, the model knows how to parse this
    # (see AccountField.php)
    with open(status_filename) as f:
        result = json.load(f)

print(json.dumps(result))
