PLUGIN_NAME=		mdns-bridge
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Bridge multicast DNS between networks (IPv4 and IPv6)
PLUGIN_MAINTAINER=	cspartalis@potatonetworks.com
PLUGIN_DEPENDS=		mdns-bridge

.include "../../Mk/plugins.mk"
