PLUGIN_NAME=		ddclient
PLUGIN_VERSION=		1.32
PLUGIN_DEPENDS=		ddclient os-dyndns
PLUGIN_COMMENT=		Dynamic DNS client (ddclient Perl backend wrapper)
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
