PLUGIN_NAME=		ddclient
PLUGIN_VERSION=		2.0
PLUGIN_DEPENDS=		os-dyndns${PLUGIN_PKGSUFFIX} ddclient
PLUGIN_COMMENT=		Dynamic DNS legacy ddclient backend
PLUGIN_OBSOLETE=	yes
PLUGIN_TIER=		3

.include "../../Mk/plugins.mk"
