PLUGIN_NAME=		dyndns
PLUGIN_VERSION=		2.0
PLUGIN_DEPENDS=		py${PLUGIN_PYTHON}-boto3
PLUGIN_COMMENT=		Dynamic DNS client
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
