[apply]
command:/usr/local/opnsense/scripts/beepselector/apply.sh
parameters:
type:script_output
message:Apply beep selector configuration

[test]
command:/usr/local/opnsense/scripts/beepselector/test.sh
parameters:
type:script_output
message:Test beep sound
