[apply]
command:/usr/local/opnsense/scripts/beepbeep/apply.sh
parameters:
type:script_output
message:Apply beep beep configuration

[test]
command:/usr/local/opnsense/scripts/beepbeep/test.sh
parameters:
type:script_output
message:Test beep sound
