[start]
command:/usr/local/opnsense/scripts/ddclient/service.sh start
type:script
message:starting ddclient

[stop]
command:/usr/local/opnsense/scripts/ddclient/service.sh stop
errors:no
type:script
message:stopping ddclient

[status]
command:/usr/local/sbin/pluginctl -s ddclient status
type:script_output
message:get ddclient status

[restart]
command:/usr/local/opnsense/scripts/ddclient/service.sh restart
type:script
message:restarting ddclient
description:Restart ddclient service

[force]
command:/usr/local/opnsense/scripts/ddclient/service.sh force
type:script
message:forcing ddclient update
description:Force ddclient update

[statistics]
command:/usr/local/opnsense/scripts/ddclient/stats
type:script_output
message:get ddclient statistics

[opnbackend.supported]
command:/usr/local/opnsense/scripts/ddclient/ddclient_opn.py -l
type:script_output
message:get ddclient statistics
