[start]
command:
    if [ -f /usr/local/opnsense/version/ddclient ]; then
        if [ -f /usr/local/etc/rc.d/ddclient ]; then /usr/local/etc/rc.d/ddclient start; fi
    else
        /usr/local/etc/rc.d/ddclient_opn start
    fi
type:script
message:starting ddclient

[stop]
command:pkill -F /var/run/ddclient.pid 2> /dev/null; /usr/local/etc/rc.d/ddclient_opn onestop 2> /dev/null
errors:no
type:script
message:stopping ddclient

[status]
command:/usr/local/sbin/pluginctl -s ddclient status
type:script_output
message:get ddclient status

[restart]
command:
    if [ -f /usr/local/opnsense/version/ddclient ]; then
        pkill -F /var/run/ddclient.pid 2> /dev/null;
        if [ -f /usr/local/etc/rc.d/ddclient ]; then /usr/local/etc/rc.d/ddclient restart; fi
    else
        /usr/local/etc/rc.d/ddclient_opn restart
    fi
type:script
message:restarting ddclient
description:Restart ddclient service

[force]
command:
    if [ -f /usr/local/opnsense/version/ddclient ]; then
        if [ -x /usr/local/sbin/ddclient ]; then /usr/local/sbin/ddclient -force; fi
    else
        rm /var/tmp/ddclient_opn.status 2>/dev/null;
        /usr/local/etc/rc.d/ddclient_opn restart 2>/dev/null
    fi
type:script
message:forcing ddclient update
description:Force ddclient update

[statistics]
command:/usr/local/opnsense/scripts/ddclient/stats
type:script_output
message:get ddclient statistics

[opnbackend.supported]
command:/usr/local/opnsense/scripts/ddclient/ddclient_opn.py -l
type:script_output
message:get ddclient statistics
