#!/bin/sh

# Beep beep - Apply Configuration
# Installs the selected beep scripts into rc.syshook.d for startup and shutdown

CONFIG_FILE="/usr/local/etc/BeepBeep/beepbeep.conf"
BEEPS_DIR="/usr/local/etc/BeepBeep/beeps"
START_HOOK="/usr/local/etc/rc.syshook.d/start/50-beep"
STOP_HOOK="/usr/local/etc/rc.syshook.d/stop/50-beep"

# Read a value from the INI-style config file
read_config() {
    local key="$1"
    if [ -f "$CONFIG_FILE" ]; then
        grep "^${key}=" "$CONFIG_FILE" | head -1 | cut -d'=' -f2-
    fi
}

# Generate a syshook script that plays a beep file
generate_hook_script() {
    local beep_selection="$1"
    local custom_path="$2"
    local hook_path="$3"
    local beep_file=""

    case "$beep_selection" in
        none)
            # Remove hook script if it exists (no beep)
            rm -f "$hook_path"
            return 0
            ;;
        custom)
            if [ -n "$custom_path" ] && [ -f "$custom_path" ]; then
                beep_file="$custom_path"
            else
                echo "{\"status\": \"error\", \"message\": \"Custom beep file not found: $custom_path\"}"
                return 1
            fi
            ;;
        *)
            beep_file="${BEEPS_DIR}/${beep_selection}"
            if [ ! -f "$beep_file" ]; then
                echo "{\"status\": \"error\", \"message\": \"Beep file not found: $beep_file\"}"
                return 1
            fi
            ;;
    esac

    # Create the hook script
    cat > "$hook_path" << EOF
#!/bin/sh
# Generated by OPNsense Beep beep plugin
# Do not edit manually - changes will be overwritten
if [ -c /dev/speaker ]; then
    cat "${beep_file}" > /dev/speaker 2>/dev/null
fi
EOF
    chmod 755 "$hook_path"
    return 0
}

# Main
enabled=$(read_config "enabled")

if [ "$enabled" != "1" ]; then
    # Disabled - remove hook scripts
    rm -f "$START_HOOK"
    rm -f "$STOP_HOOK"
    echo "{\"status\": \"ok\", \"message\": \"Beep beep disabled, hooks removed.\"}"
    exit 0
fi

# Ensure syshook directories exist
mkdir -p /usr/local/etc/rc.syshook.d/start
mkdir -p /usr/local/etc/rc.syshook.d/stop

start_beep=$(read_config "start_beep")
stop_beep=$(read_config "stop_beep")
start_custom=$(read_config "start_beep_custom")
stop_custom=$(read_config "stop_beep_custom")

errors=""

# Apply start beep
if ! generate_hook_script "$start_beep" "$start_custom" "$START_HOOK"; then
    errors="start beep error"
fi

# Apply stop beep
if ! generate_hook_script "$stop_beep" "$stop_custom" "$STOP_HOOK"; then
    if [ -n "$errors" ]; then
        errors="$errors, stop beep error"
    else
        errors="stop beep error"
    fi
fi

if [ -n "$errors" ]; then
    echo "{\"status\": \"error\", \"message\": \"Errors applying configuration: $errors\"}"
else
    echo "{\"status\": \"ok\", \"message\": \"Beep configuration applied successfully.\"}"
fi
